from django.conf.urls import url
from doctor import views

urlpatterns = [
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^dashboard/support/$', views.HelpSupport.as_view(), name='help'),
    url(r'^dashboard/messagecenter/$', views.MessageCenter.as_view(), name='messages'),
    url(r'^dashboard/support/$', views.HelpSupport.as_view(), name='help'),
    url(r'^my_account/history/$', views.HistoryView.as_view(), name='history'),
    url(r'^my_account/password/$', views.PasswordView.as_view(), name='password'),
    url(r'^my_account/paymenthistory/$', views.PaymentHistoryView.as_view(), name='payment_history'),
    url(r'^my_account/payment/$', views.PaymentView.as_view(), name='payment'),
    url(r'^my_account/details/$', views.DetailsView.as_view(), name='my_account'),
    url(r'^profile/specialty/$', views.SpecialtyView.as_view(), name='specialty'),
    url(r'^profile/specialty/(?P<id_specialty>\d+)/$', views.SpecialtyView.as_view(), name='specialty_delete'),
    url(r'^profile/experience/$', views.ExperienceView.as_view(), name='experience'),
    url(r'^profile/experience/(?P<id_experience>\d+)/$', views.ExperienceView.as_view(), name='experience_delete'),
    url(r'^schedule/calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^schedule/time/$', views.TimeView.as_view(), name='time'),
    url(r'^schedule/time/(?P<id_appointment_date>\d+)/$', views.TimeView.as_view(), name='reschedule_time'),
    url(r'^schedule/calendar/(?P<current_date>[\d-]*)/(?P<id_time>\d+)/$',
        views.CalendarView.as_view(), name='timedel'),
    url(r'^schedule/calendar/(?P<current_date>[\d-]*)/$', views.CalendarView.as_view(), name='calendar_date'),
    url(r'^schedule/appointments/$', views.AppointmentsView.as_view(), name='appointments'),
    url(r'^schedule/appointments/status/(?P<id_appointment>\d+)/(?P<status>\d+)/$',
        views.AppointmentsView.as_view(), name='appointment_status'),
    url(r'^schedule/appointments/(?P<id_appointment>\d+)/$',
        views.AppointmentsView.as_view(), name='appointment_info'),
    url(r'^schedule/appointments/open/(?P<id_appointment>\d+)/$',
        views.AppointmentsView.as_view(), name='appointment_open'),
    url(r'^schedule/reschedule/(?P<id_appointment>\d+)/$',
        views.AppointmentSchedule.as_view(), name='appointment_reschedule'),
    url(r'^case/(?P<type>\w+)/$', views.CaseListView.as_view(), name='case'),
    url(r'^case/open/$', views.CaseListView.as_view(), name='case_open'),
    url(r'^case/view/(?P<id_case>\d+)/$', views.EditCaseView.as_view(), name='edit_case'),
    # url(r'^case/del/(?P<id_case>\d+)/(?P<id_test>\d+)/$', views.EditCaseView.as_view(), name='del_test'),
    url(r'^case/create/new/$', views.CaseView.as_view(), name='new_case'),
]
