from django.conf.urls import url
from patient import views

urlpatterns = [
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^dashboard/talk-to-a-doctor/$', views.TalkToADoctor.as_view(), name='talk_to_a_doctor'),
    url(r'^dashboard/history/$', views.MyHealthHistory.as_view(), name='my_health_history'),
    url(r'^dashboard/lifestyle/$', views.MyLifestyle.as_view(), name='my_lifestyle'),
    url(r'^dashboard/family/$', views.MyFamilyHistory.as_view(), name='my_family_history'),
    url(r'^dashboard/support/$', views.HelpSupport.as_view(), name='help'),
    url(r'^dashboard/messagecenter/$', views.MessageCenter.as_view(), name='messages'),
    url(r'^dashboard/history/$', views.MyHealthHistory.as_view(), name='my_health_history'),
    url(r'^dashboard/lifestyle/$', views.MyLifestyle.as_view(), name='my_lifestyle'),
    url(r'^dashboard/family/$', views.MyFamilyHistory.as_view(), name='my_family_history'),
    url(r'^dashboard/records/$', views.MyRecords.as_view(), name='my_records'),
    url(r'^dashboard/records/(?P<id_file>.+)/$', views.MyRecords.as_view(), name='my_records_delete'),
    url(r'^dashboard/support/$', views.HelpSupport.as_view(), name='help'),
    url(r'^dashboard/consultations/$', views.ConsultationView.as_view(), name='consultation'),
    url(r'^dashboard/consultations/status/(?P<id_appointment>\d+)/(?P<status>\d+)/$',
        views.ConsultationView.as_view(), name='consultation_status'),
    url(r'^dashboard/consultations/edit/(?P<pk>\d+)/$',
        views.ConsultationEdit.as_view(), name='consultation_edit'),
    url(r'^my_account/history/$', views.HistoryView.as_view(), name='history'),
    url(r'^my_account/password/$', views.PasswordView.as_view(), name='password'),
    url(r'^my_account/billing/$', views.BillingView.as_view(), name='billing'),
    url(r'^my_account/details/$', views.DetailsView.as_view(), name='my_account'),
    url(r'^appointment_request/(?P<pk>[0-9]+)/$', views.PatientAppointmentView.as_view(), name='appointment_request'),
    url(r'^appointment_process/$', views.PatientAppointmentProcessView.as_view(), name='appointment_process'),
    url(r'^appointment_process/confirmation/$', views.ConfirmAppointmentProcessView.as_view(), name='confirmation'),
    url(r'^doctor/(?P<pk>[0-9]+)/$', views.DoctorDetailView.as_view(), name='detail_doctor'),
    url(r'^date/(?P<pk>[0-9]+)/$', views.AppointmentTimeView.as_view(), name='date_appointment'),
    url(r'^all_doctors/$', views.get_all_doctors_json, name='all_doctors'),
    url(r'^doctor_appointment_date/$', views.get_doctor_appointment_date, name='doctor_date'),
    url(r'^doctor_appointment_time/$', views.get_doctor_appointment_time, name='doctor_time'),
]
